export type EmployeeStatus = "hired" | "invited" | "onboarding" | "active" | "on_leave" | "terminated";

// ─── ROLE-BASED DATA ────────────────────────────────────────

export type UserRole = "super_admin" | "owner" | "manager" | "employee" | "parent";

export interface TestUser {
  id: string;
  name: string;
  email: string;
  password: string;
  role: UserRole;
  companyId: string;
  locationId?: string;
  employeeId: string | null;
  position: string;
  hourlyWage?: number;
  /** 'hourly' | 'salary' — carried from wizard so preview works before the DB is consulted. */
  payType?: string;
  status?: EmployeeStatus;
  onLeaveReason?: string;
  onLeaveDate?: string;
  expectedReturnDate?: string;
  terminatedAt?: string;
  terminationReason?: string;
  lastWorkingDay?: string;
  terminatedBy?: string;
}

export interface Company {
  id: string;
  name: string;
  type: "headquarters" | "daycare";
  locationId?: string;
  address?: string;
  latitude?: number;
  longitude?: number;
  payFrequency?: string; // "BiWeekly" | "Weekly" | "SemiMonthly" | "Monthly"
}

export interface Location {
  id: string;
  name: string;
  organizationId: string;
  address: string;
  latitude: number;
  longitude: number;
}

export interface Child {
  id: string;
  name: string;
  parentId: string;
  age: number;
  checkedIn: boolean;
  checkInTime?: string;
}

function uid() {
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

// ─── EASYTEAM HOURS BRIDGE ───────────────────────────────────

export interface TimesheetEntry {
  employeeId: string;
  companyId: string;
  periodKey: string; // "YYYY-MM-DD/YYYY-MM-DD"
  hoursWorked: number;
  breakDeduction: number;
  approvedHours: number;
  source: "easyteam" | "seeded" | "estimated";
  syncedAt: string;
  managerApproved?: boolean;
  approvedAt?: string;
  approvedByUserId?: string;
}

const timesheetHours = new Map<string, TimesheetEntry>(); // key: `${employeeId}::${periodKey}`
const etUuidToEmployeeId = new Map<string, string>([
  // Arbab Nasir was added directly via EasyTeam UI (not our app), so his UUID is known but boot sync won't register him
  ["2f1c0890-0eea-4eb6-9cb2-93ce5c45ba59", "EMP-RAINBOW-004"],
]);

// ─── ROLLFI INTEGRATION STATE ─────────────────────────────────

export interface RollfiCompanyRecord {
  rollfiCompanyId: string;
  rollfiLocationId: string;
  onboardedAt: string;
  ein?: string;
  ownerSsn?: string;
}

export interface RollfiEmployeeRecord {
  rollfiUserId: string;
  rollfiWageId?: string;
  onboardedAt: string;
}

export interface ActivityEvent {
  id: string;
  companyId: string;
  type: string;
  description: string;
  actorName?: string;
  actorRole?: string;
  createdAt: string;
}

// ─── PEOPLE MODULE TYPES ──────────────────────────────────────

export interface Department {
  id: string;
  companyId: string;
  name: string;
  type: "standard" | "daycare" | "custom";
  isDefault: boolean;
  isActive: boolean;
  createdAt: string;
}

export interface OnboardingTask {
  id: string;
  employeeId: string;
  companyId: string;
  taskName: string;
  description?: string;
  category: "hr_payroll" | "manager" | "it" | "compliance" | "daycare_compliance";
  stage: "preboarding" | "documents" | "training" | "equipment" | "manager_tasks" | "compliance" | "ready_to_start";
  assignedToRole: "hr" | "manager" | "employee" | "admin" | "it";
  assignedToUserId?: string;
  status: "pending" | "in_progress" | "completed" | "overdue" | "skipped";
  isRequired: boolean;
  dueDate?: string;
  dueDaysAfterHire: number;
  completedAt?: string;
  completedBy?: string;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface ComplianceItem {
  id: string;
  employeeId: string;
  companyId: string;
  type: "i9" | "w4" | "state_w4" | "direct_deposit" | "background_check" | "handbook" | "policy" | "training" | "certification" | "fingerprint" | "custom";
  name: string;
  status: "not_started" | "pending" | "completed" | "expired" | "waived";
  isRequired: boolean;
  completedAt?: string;
  expiryDate?: string;
  linkedDocumentId?: string;
  linkedTaskId?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface EmergencyContact {
  id: string;
  employeeId: string;
  companyId: string;
  contactType: "primary" | "secondary";
  name: string;
  relationship: string;
  phoneNumber: string;
  alternatePhone?: string;
  email?: string;
  address?: string;
  physicianName?: string;
  physicianPhone?: string;
  insuranceProvider?: string;
  insurancePolicyNumber?: string;
  createdAt: string;
  updatedAt: string;
}

export interface EmployeeDocument {
  id: string;
  employeeId: string;
  companyId: string;
  documentName: string;
  documentType: "i9" | "w4" | "handbook" | "policy" | "offer_letter" | "nda" | "license" | "certification" | "background_check" | "tax_form" | "custom";
  customTypeName?: string;
  fileName: string;
  fileUrl: string;
  fileSize?: number;
  mimeType?: string;
  status: "pending" | "uploaded" | "verified" | "rejected" | "expired";
  uploadedAt: string;
  uploadedBy: string;
  verifiedAt?: string;
  verifiedBy?: string;
  expiryDate?: string;
  requiresSignature: boolean;
  signedAt?: string;
  signedBy?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface PeopleActivityEntry {
  id: string;
  companyId: string;
  employeeId?: string;
  action: string;
  description: string;
  category: "employee" | "onboarding" | "compliance" | "payroll" | "document" | "system";
  performedBy: string;
  metadata?: Record<string, unknown>;
  timestamp: string;
}

const rollfiCompanies = new Map<string, RollfiCompanyRecord>();
const rollfiEmployees = new Map<string, RollfiEmployeeRecord>();

// ─── PEOPLE MODULE STORAGE ────────────────────────────────────
const departments: Department[] = [];
const onboardingTasks: OnboardingTask[] = [];
const complianceItems: ComplianceItem[] = [];
const emergencyContacts: EmergencyContact[] = [];
const employeeDocuments: EmployeeDocument[] = [];
const peopleActivityLog: PeopleActivityEntry[] = [];

// ─── CLIENTS / CLIENT-EMPLOYEES (removed) ───────────────────
// Legacy in-memory clients[] and ClientEmployee[] are gone. Daycare companies now live in
// the DB `companies` table and their staff in the DB `employees` table (unified model).
// The HTTP /clients endpoints in routes/clients.ts project over those tables for back-compat.

// ─── TEST USERS ──────────────────────────────────────────────

const testUsers: TestUser[] = [
  { id: "USER-001", name: "Joanne Indiviglio", email: "joanne@brightbridgeassist.com", password: "Admin123!", role: "super_admin", companyId: "ORG-BRIGHTBRIDGE", employeeId: "ADMIN-JOANNE", position: "Super Admin" },
  { id: "USER-002", name: "Susan Manager", email: "manager@sunshine.com", password: "Manager123!", role: "owner", companyId: "ORG-SUNSHINE", locationId: "LOC-SUNSHINE", employeeId: "MGR-SUNSHINE-001", position: "Daycare Manager" },
  { id: "USER-003", name: "Mike Manager", email: "manager@rainbow.com", password: "Manager123!", role: "owner", companyId: "ORG-RAINBOW", locationId: "LOC-RAINBOW", employeeId: "MGR-RAINBOW-001", position: "Daycare Manager" },
  // NOTE: hourlyWage here is a LAST-RESORT FALLBACK only.
  // For any employee that has a DB record in the `employees` table, the DB wage always wins.
  // These values are only used if the employee has no `employees` row at all (e.g. during
  // the very first boot before the seed write, or for record-less test employees).
  { id: "USER-004", name: "John Smith", email: "john@sunshine.com", password: "Staff123!", role: "employee", companyId: "ORG-SUNSHINE", locationId: "LOC-SUNSHINE", employeeId: "EMP-SUNSHINE-001", position: "Teacher", hourlyWage: 2000 },
  { id: "USER-005", name: "Mary Johnson", email: "mary@sunshine.com", password: "Staff123!", role: "employee", companyId: "ORG-SUNSHINE", locationId: "LOC-SUNSHINE", employeeId: "EMP-SUNSHINE-002", position: "Assistant", hourlyWage: 1500 },
  { id: "USER-006", name: "Tom Wilson", email: "tom@rainbow.com", password: "Staff123!", role: "employee", companyId: "ORG-RAINBOW", locationId: "LOC-RAINBOW", employeeId: "EMP-RAINBOW-001", position: "Teacher", hourlyWage: 1800 },
  { id: "USER-008", name: "Ali Husnain", email: "ali@rainbow.com", password: "Staff123!", role: "employee", companyId: "ORG-RAINBOW", locationId: "LOC-RAINBOW", employeeId: "EMP-RAINBOW-002", position: "Lead Teacher", hourlyWage: 1800 },
  { id: "USER-009", name: "Lisa Chen", email: "lisa.chen@rainbow.com", password: "Staff123!", role: "employee", companyId: "ORG-RAINBOW", locationId: "LOC-RAINBOW", employeeId: "EMP-RAINBOW-003", position: "Teaching Assistant", hourlyWage: 1400 },
  { id: "USER-010", name: "Arbab Nasir", email: "arbab@rainbow.com", password: "Staff123!", role: "employee", companyId: "ORG-RAINBOW", locationId: "LOC-RAINBOW", employeeId: "EMP-RAINBOW-004", position: "Staff", hourlyWage: 1500 },
  { id: "USER-007", name: "Sarah Parent", email: "sarah@parent.com", password: "Parent123!", role: "parent", companyId: "ORG-SUNSHINE", employeeId: null, position: "Parent" },
];

// ─── COMPANIES ───────────────────────────────────────────────

const companies: Company[] = [
  { id: "ORG-BRIGHTBRIDGE", name: "BrightBridge Assist", type: "headquarters", payFrequency: "BiWeekly" },
  { id: "ORG-SUNSHINE", name: "Sunshine Daycare Centre", type: "daycare", locationId: "LOC-SUNSHINE", address: "123 Main St, Newark NJ", latitude: 40.7357, longitude: -74.1724, payFrequency: "BiWeekly" },
  { id: "ORG-RAINBOW", name: "Rainbow Kids Daycare", type: "daycare", locationId: "LOC-RAINBOW", address: "456 Oak Ave, Jersey City NJ", latitude: 40.7178, longitude: -74.0431, payFrequency: "BiWeekly" },
];

// ─── LOCATIONS ───────────────────────────────────────────────

const locations: Location[] = [
  { id: "LOC-SUNSHINE", name: "Sunshine Daycare Centre", organizationId: "ORG-SUNSHINE", address: "123 Main St, Newark NJ", latitude: 40.7357, longitude: -74.1724 },
  { id: "LOC-RAINBOW", name: "Rainbow Kids Daycare", organizationId: "ORG-RAINBOW", address: "456 Oak Ave, Jersey City NJ", latitude: 40.7178, longitude: -74.0431 },
];

// ─── ACTIVITY LOG ─────────────────────────────────────────────

const activityLog: ActivityEvent[] = [];

// ─── CHILDREN ────────────────────────────────────────────────

const children: Child[] = [
  { id: "CHILD-001", name: "Emma Johnson", parentId: "USER-007", age: 4, checkedIn: false },
  { id: "CHILD-002", name: "Liam Johnson", parentId: "USER-007", age: 6, checkedIn: false },
];

// ─── STORE ───────────────────────────────────────────────────

export const store = {
  // ── Auth Users ──
  getCompanyById(id: string): Company | undefined {
    return companies.find((c) => c.id === id);
  },
  getUserByEmail(email: string): TestUser | undefined {
    return testUsers.find((u) => u.email.toLowerCase() === email.toLowerCase());
  },
  getUserById(id: string): Omit<TestUser, "password"> | undefined {
    const user = testUsers.find((u) => u.id === id);
    if (!user) return undefined;
    const { password: _p, ...safe } = user;
    return safe;
  },
  getAllUsersPublic(): Omit<TestUser, "password">[] {
    return testUsers.map(({ password: _p, ...safe }) => safe);
  },
  getUsersForCompany(companyId: string): Omit<TestUser, "password">[] {
    return testUsers.filter((u) => u.companyId === companyId && u.employeeId !== null).map(({ password: _p, ...safe }) => safe);
  },
  getAllStaffUsers(): Omit<TestUser, "password">[] {
    return testUsers.filter((u) => u.employeeId !== null && u.companyId !== "").map(({ password: _p, ...safe }) => safe);
  },
  getRawUser(id: string): TestUser | undefined {
    return testUsers.find((u) => u.id === id);
  },
  addTestUser(user: TestUser): void {
    const existing = testUsers.find((u) => u.email.toLowerCase() === user.email.toLowerCase());
    if (!existing) testUsers.push(user);
  },

  // ── EasyTeam UUID ↔ internal employee ID mapping ──
  setEasyTeamUuidMapping(etUuid: string, internalEmployeeId: string): void {
    etUuidToEmployeeId.set(etUuid, internalEmployeeId);
  },
  resolveEasyTeamUuid(etUuid: string): string {
    return etUuidToEmployeeId.get(etUuid) ?? etUuid;
  },

  // ── EasyTeam Hours Bridge ──
  getTimesheetKey(employeeId: string, periodKey: string): string { return `${employeeId}::${periodKey}`; },
  getTimesheetEntry(employeeId: string, periodKey: string): TimesheetEntry | undefined {
    return timesheetHours.get(`${employeeId}::${periodKey}`);
  },
  setTimesheetEntry(entry: TimesheetEntry): void {
    timesheetHours.set(`${entry.employeeId}::${entry.periodKey}`, entry);
  },
  getTimesheetEntriesForPeriod(periodKey: string): TimesheetEntry[] {
    return Array.from(timesheetHours.values()).filter((e) => e.periodKey === periodKey);
  },
  /** Returns the most recently synced timesheet entry for an employee across ALL period keys. */
  getLatestTimesheetEntry(employeeId: string, companyId?: string): TimesheetEntry | undefined {
    let latest: TimesheetEntry | undefined;
    for (const entry of timesheetHours.values()) {
      if (entry.employeeId !== employeeId) continue;
      if (companyId && entry.companyId !== companyId) continue;
      if (!latest || entry.syncedAt > latest.syncedAt) latest = entry;
    }
    return latest;
  },
  clearTimesheetEntriesForCompanyPeriod(companyId: string, periodKey: string): void {
    for (const [key, entry] of timesheetHours.entries()) {
      if (entry.companyId === companyId && entry.periodKey === periodKey) {
        timesheetHours.delete(key);
      }
    }
  },
  seedTimesheetHours(periodKey: string): TimesheetEntry[] {
    // Only seed hourly employees (not managers/admins) with realistic hours.
    // Tom Wilson's hours match EasyTeam sandbox data (1.95 h clock-in).
    // All other employees get plausible part-shift hours so the demo looks real.
    const realisticHours: Record<string, { h: number; b: number }> = {
      "EMP-RAINBOW-001": { h: 1.95, b: 0 },    // Tom Wilson — matches EasyTeam sandbox
      "EMP-SUNSHINE-001": { h: 3.5,  b: 0.5 }, // John Smith
      "EMP-SUNSHINE-002": { h: 4.0,  b: 0.5 }, // Mary Johnson
    };
    const staff = testUsers.filter(
      (u) => u.employeeId && u.role === "employee"
    );
    const seeded: TimesheetEntry[] = [];
    staff.forEach((u) => {
      const defaults = realisticHours[u.employeeId!];
      // Only seed employees with explicit realistic-hours data.
      // Employees not in the map (e.g. newly added Ali, Lisa) start with 0 seeded hours
      // so their real clocked time from EasyTeam is the only source of truth.
      if (!defaults) return;
      const hoursWorked    = defaults.h;
      const breakDeduction = defaults.b;
      const approvedHours  = Math.max(0, hoursWorked - breakDeduction);
      const entry: TimesheetEntry = {
        employeeId: u.employeeId!,
        companyId: u.companyId,
        periodKey,
        hoursWorked,
        breakDeduction,
        approvedHours,
        source: "seeded",
        syncedAt: new Date().toISOString(),
      };
      timesheetHours.set(`${u.employeeId!}::${periodKey}`, entry);
      seeded.push(entry);
    });
    return seeded;
  },
  approveTimesheetEntries(periodKey: string, companyId: string, approvedByUserId: string): TimesheetEntry[] {
    const entries = Array.from(timesheetHours.values()).filter(
      (e) => e.periodKey === periodKey && e.companyId === companyId
    );
    const now = new Date().toISOString();
    for (const entry of entries) {
      entry.managerApproved = true;
      entry.approvedAt = now;
      entry.approvedByUserId = approvedByUserId;
      timesheetHours.set(`${entry.employeeId}::${periodKey}`, entry);
    }
    return entries;
  },
  clearTimesheetHours(periodKey?: string): void {
    if (periodKey) {
      for (const key of timesheetHours.keys()) { if (key.endsWith(`::${periodKey}`)) timesheetHours.delete(key); }
    } else {
      timesheetHours.clear();
    }
  },

  // ── Staff Users (payroll employees) ──
  createStaffUser(data: { name: string; email: string; position: string; hourlyWage: number; companyId: string }): Omit<TestUser, "password"> {
    const id = `USER-${uid().toUpperCase()}`;
    const employeeId = `EMP-${uid().toUpperCase()}`;
    const company = companies.find((c) => c.id === data.companyId);
    const locationId = company?.locationId;
    const newUser: TestUser = {
      id,
      name: data.name,
      email: data.email,
      password: "Staff123!",
      role: "employee",
      companyId: data.companyId,
      locationId,
      employeeId,
      position: data.position,
      hourlyWage: data.hourlyWage,
    };
    testUsers.push(newUser);
    const { password: _p, ...safe } = newUser;
    return safe;
  },
  createManagerUser(data: { name: string; email: string; position: string; companyId: string; password?: string }): { user: Omit<TestUser, "password">; password: string } {
    const id = `USER-DYN-${Date.now()}`;
    const employeeId = `MGR-${uid().toUpperCase()}`;
    const company = companies.find((c) => c.id === data.companyId);
    const locationId = company?.locationId;
    const password = data.password ?? "Manager123!";
    const newUser: TestUser = {
      id,
      name: data.name,
      email: data.email,
      password,
      role: "owner",
      companyId: data.companyId,
      locationId,
      employeeId,
      position: data.position,
    };
    testUsers.push(newUser);
    const { password: _p, ...safe } = newUser;
    return { user: safe, password };
  },
  updateTestUser(userId: string, updates: Partial<Pick<TestUser, "name" | "email" | "password" | "position">>): boolean {
    const idx = testUsers.findIndex((u) => u.id === userId);
    if (idx === -1) return false;
    testUsers[idx] = { ...testUsers[idx]!, ...updates };
    return true;
  },
  getTestUserById(userId: string): TestUser | undefined {
    return testUsers.find((u) => u.id === userId);
  },
  deleteStaffUser(userId: string): boolean {
    const idx = testUsers.findIndex((u) => u.id === userId && (u.role === "employee" || u.role === "owner" || u.role === "manager"));
    if (idx === -1) return false;
    testUsers.splice(idx, 1);
    return true;
  },
  updateEmployeeStatus(
    employeeId: string,
    status: EmployeeStatus,
    additionalFields?: Partial<Pick<TestUser, "onLeaveReason" | "onLeaveDate" | "expectedReturnDate" | "terminatedAt" | "terminationReason" | "lastWorkingDay" | "terminatedBy">>
  ): boolean {
    const idx = testUsers.findIndex((u) => u.employeeId === employeeId);
    if (idx === -1) return false;
    testUsers[idx] = { ...testUsers[idx]!, status, ...additionalFields };
    return true;
  },

  // ── Companies ──
  getCompany(id: string): Company | undefined { return companies.find((c) => c.id === id); },
  getCompanies(): Company[] { return companies; },
  getDaycareCompanies(): Company[] { return companies.filter((c) => c.type === "daycare"); },

  // ── Locations ──
  getLocation(id: string): Location | undefined { return locations.find((l) => l.id === id); },
  getLocations(): Location[] { return locations; },

  // ── Rollfi ──
  getRollfiCompany(companyId: string): RollfiCompanyRecord | undefined { return rollfiCompanies.get(companyId); },
  setRollfiCompany(companyId: string, record: RollfiCompanyRecord): void { rollfiCompanies.set(companyId, record); },
  getRollfiEmployee(employeeId: string): RollfiEmployeeRecord | undefined { return rollfiEmployees.get(employeeId); },
  setRollfiEmployee(employeeId: string, record: RollfiEmployeeRecord): void { rollfiEmployees.set(employeeId, record); },

  // ── Activity log ──
  logActivity(event: Omit<ActivityEvent, "id" | "createdAt">): void {
    const entry: ActivityEvent = {
      id: `act-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
      createdAt: new Date().toISOString(),
      ...event,
    };
    activityLog.unshift(entry);
    if (activityLog.length > 300) activityLog.splice(300);
  },
  getActivity(companyId: string, limit = 50): ActivityEvent[] {
    return activityLog.filter((e) => e.companyId === companyId).slice(0, limit);
  },

  // ── People: Departments ──
  getDepartments(companyId: string): Department[] { return departments.filter((d) => d.companyId === companyId && d.isActive); },
  getDepartmentById(id: string): Department | undefined { return departments.find((d) => d.id === id); },
  addDepartment(d: Department): void { departments.push(d); },
  updateDepartment(id: string, updates: Partial<Department>): boolean {
    const idx = departments.findIndex((d) => d.id === id);
    if (idx === -1) return false;
    departments[idx] = { ...departments[idx]!, ...updates };
    return true;
  },
  deleteDepartment(id: string): boolean {
    const idx = departments.findIndex((d) => d.id === id);
    if (idx === -1) return false;
    departments[idx]!.isActive = false;
    return true;
  },
  hasDepartmentsForCompany(companyId: string): boolean { return departments.some((d) => d.companyId === companyId); },

  // ── People: Onboarding Tasks ──
  getOnboardingTasks(filter: { employeeId?: string; companyId?: string; status?: string; assignedToUserId?: string }): OnboardingTask[] {
    return onboardingTasks.filter((t) => {
      if (filter.employeeId && t.employeeId !== filter.employeeId) return false;
      if (filter.companyId && t.companyId !== filter.companyId) return false;
      if (filter.status && t.status !== filter.status) return false;
      if (filter.assignedToUserId && t.assignedToUserId !== filter.assignedToUserId) return false;
      return true;
    });
  },
  getOnboardingTaskById(id: string): OnboardingTask | undefined { return onboardingTasks.find((t) => t.id === id); },
  addOnboardingTasks(tasks: OnboardingTask[]): void { onboardingTasks.push(...tasks); },
  updateOnboardingTask(id: string, updates: Partial<OnboardingTask>): boolean {
    const idx = onboardingTasks.findIndex((t) => t.id === id);
    if (idx === -1) return false;
    onboardingTasks[idx] = { ...onboardingTasks[idx]!, ...updates, updatedAt: new Date().toISOString() };
    return true;
  },

  // ── People: Compliance Items ──
  getComplianceItems(filter: { employeeId?: string; companyId?: string }): ComplianceItem[] {
    return complianceItems.filter((c) => {
      if (filter.employeeId && c.employeeId !== filter.employeeId) return false;
      if (filter.companyId && c.companyId !== filter.companyId) return false;
      return true;
    });
  },
  getComplianceItemById(id: string): ComplianceItem | undefined { return complianceItems.find((c) => c.id === id); },
  addComplianceItems(items: ComplianceItem[]): void { complianceItems.push(...items); },
  updateComplianceItem(id: string, updates: Partial<ComplianceItem>): boolean {
    const idx = complianceItems.findIndex((c) => c.id === id);
    if (idx === -1) return false;
    complianceItems[idx] = { ...complianceItems[idx]!, ...updates, updatedAt: new Date().toISOString() };
    return true;
  },

  // ── People: Emergency Contacts ──
  getEmergencyContacts(employeeId: string): EmergencyContact[] { return emergencyContacts.filter((c) => c.employeeId === employeeId); },
  getEmergencyContactById(id: string): EmergencyContact | undefined { return emergencyContacts.find((c) => c.id === id); },
  addEmergencyContact(c: EmergencyContact): void { emergencyContacts.push(c); },
  updateEmergencyContact(id: string, updates: Partial<EmergencyContact>): boolean {
    const idx = emergencyContacts.findIndex((c) => c.id === id);
    if (idx === -1) return false;
    emergencyContacts[idx] = { ...emergencyContacts[idx]!, ...updates, updatedAt: new Date().toISOString() };
    return true;
  },
  deleteEmergencyContact(id: string): boolean {
    const idx = emergencyContacts.findIndex((c) => c.id === id);
    if (idx === -1) return false;
    emergencyContacts.splice(idx, 1);
    return true;
  },

  // ── People: Documents ──
  getDocuments(filter: { employeeId?: string; companyId?: string }): EmployeeDocument[] {
    return employeeDocuments.filter((d) => {
      if (filter.employeeId && d.employeeId !== filter.employeeId) return false;
      if (filter.companyId && d.companyId !== filter.companyId) return false;
      return true;
    });
  },
  getDocumentById(id: string): EmployeeDocument | undefined { return employeeDocuments.find((d) => d.id === id); },
  addDocument(d: EmployeeDocument): void { employeeDocuments.push(d); },
  updateDocument(id: string, updates: Partial<EmployeeDocument>): boolean {
    const idx = employeeDocuments.findIndex((d) => d.id === id);
    if (idx === -1) return false;
    employeeDocuments[idx] = { ...employeeDocuments[idx]!, ...updates, updatedAt: new Date().toISOString() };
    return true;
  },

  // ── People: Activity Log ──
  logPeopleActivity(entry: Omit<PeopleActivityEntry, "id" | "timestamp">): void {
    const newEntry: PeopleActivityEntry = {
      id: `pal-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
      timestamp: new Date().toISOString(),
      ...entry,
    };
    peopleActivityLog.unshift(newEntry);
    if (peopleActivityLog.length > 500) peopleActivityLog.splice(500);
  },
  getPeopleActivity(filter: { companyId: string; employeeId?: string; category?: string; limit?: number }): PeopleActivityEntry[] {
    let results = peopleActivityLog.filter((e) => {
      if (e.companyId !== filter.companyId) return false;
      if (filter.employeeId && e.employeeId !== filter.employeeId) return false;
      if (filter.category && e.category !== filter.category) return false;
      return true;
    });
    return results.slice(0, filter.limit ?? 20);
  },

  // ── Children ──
  getChildrenForParent(parentId: string): Child[] { return children.filter((c) => c.parentId === parentId); },
  checkInChild(childId: string): boolean {
    const child = children.find((c) => c.id === childId);
    if (!child) return false;
    child.checkedIn = true;
    child.checkInTime = new Date().toISOString();
    return true;
  },
  checkOutChild(childId: string): boolean {
    const child = children.find((c) => c.id === childId);
    if (!child) return false;
    child.checkedIn = false;
    child.checkInTime = undefined;
    return true;
  },
};
